### PR TITLE
[PART1] French Translation

### PR DESCRIPTION
**Pull request by Genetik57**
I need much more time for the strings.xml file

### CODE REVIEW

**Comment by jhonboy121** [comment]
You shouldn't translate normal strings.xml as it is done by Google and avoids merge conflicts when merging new aosp tags. Only translate krypton_strings.xml

**Comment by jhonboy121** [comment]
Force push removing strings.xml translation

**Comment by Genetik57** [comment]
Hello,

So you can merge I wouldn't translate strings.xml

If I remove the strings.xml I lost the french translation

**Comment by jhonboy121** [comment]
Well I mentioned the wrong file. You edited the arrays.xml file, which we usually don't modify, since it is directly from aosp and modifying it will probably result in merge conflicts later when we merge new aosp tags. So restore the old arrays.xml and then force push. I'll merge after that. Only translate files with prefix krypton_ , although in some repos like KryptonSettings it is just strings.xml but it is entirely our contribution and not from aosp.

**Comment by Genetik57** [comment]
Fixed ;)

**Pull request merged**
